import { Config } from "./types";

export const atkPreset = [
  {
    id: "0",
    title: "structural",
    values: [
      "label",
      "component",
      "parentlabel",
      "parentcomponent",
      "region",
      "position",
    ],
  },
  {
    id: "1",
    title: "document",
    values: ["document_id", "document_title", "document_type"],
  },
  {
    id: "2",
    title: "linkable",
    values: ["href"],
  },
  {
    id: "3",
    title: "toggleable",
    values: ["checked"],
  },
  {
    id: "4",
    title: "facetable",
    values: ["facet"],
  },
  {
    id: "5",
    title: "universal",
    values: ["pathname", "environment", "project", "name"],
  },
  {
    id: "6",
    title: "super",
    values: [
      "email",
      "user_segment",
      "role",
      "package",
      "site_key",
      "id",
      "external_id",
      "extcode",
    ],
  },
  {
    id: "7",
    title: "mixpanel",
    values: [
      "$browser",
      "$browser_version",
      "$current_url",
      "$device",
      "$device_id",
      "$initial_referrer",
      "$initial_referring_domain",
      "$insert_id",
      "$insert_id",
      "$lib_version",
      "$os",
      "$referrer",
      "$referring_domain",
      "$screen_height",
      "$screen_width",
      "$search_engine",
      "$user_id",
      "distinct_id",
      "first_visited_at",
      "mp_lib",
      "mp_sent_by_lib_version",
      "time",
      "token",
    ],
  },
] satisfies Config[];

export const mixpanelPreset = [
  {
    id: "7",
    title: "mixpanel",
    values: [
      "$browser",
      "$browser_version",
      "$current_url",
      "$device",
      "$device_id",
      "$initial_referrer",
      "$initial_referring_domain",
      "$insert_id",
      "$insert_id",
      "$lib_version",
      "$os",
      "$referrer",
      "$referring_domain",
      "$screen_height",
      "$screen_width",
      "$search_engine",
      "$user_id",
      "distinct_id",
      "first_visited_at",
      "mp_lib",
      "mp_sent_by_lib_version",
      "time",
      "token",
    ],
  },
] satisfies Config[];
